# .ruff.toml or ruff.toml

line-length = 120
indent-width = 4

[lint]
select = ["E", "F", "W"]
ignore = []

fixable = ["ALL"]
unfixable = []

[format]
indent-style = "space"

skip-magic-trailing-comma = false

docstring-code-format = true
